const exerciseNames = [
  "Push-up",
  "Pull-up",
  "Squats",
  "Deadlift",
  "Bench Press",
  "Dumbell Press",
  "Lunges",
  "Plank",
  "Curls",
  "Jumping Jacks",
  "Burpees",
  "Mountain Climbers",
  "Sit-ups",
  "Russian Twists",
  "Box Jumps",
  "Tricep Dips",
  "Shoulder Press",
  "Leg Press",
  "Hammer Curls",
  "Calf Raises",
  "Front Squats",
  "Dumbbell Rows",
  "Lat Pulldowns",
  "Leg Extensions",
  "Skull Crushers",
  "Flutter Kicks",
  "Reverse Crunches",
  "Kettlebell Swings",
  "Seated Cable Rows",
  "Hanging Leg Raises",
  "Bicep Hammer Curls",
  "Bicep Curls",
  "Incline Bench Press",
  "Incline Dumbell Press",
  "Plank Jacks",
  "Side Plank",
  "Superman Exercise",
  "Step-ups",
  "Walking Lunges",
  "Dumbbell Flyes",
  "Romanian Deadlift",
  "Plank to Push-up",
  "Russian Deadlift",
  "Dumbbell Pullover",
  "Side Lateral Raises",
  "Leg Curl",
  "Medicine Ball Slams",
  "Battle Ropes",
  "Crunches",
  "Cable Crunches",
  "Good Mornings",
  "Face Pulls",
  "Sumo Deadlift",
  "Reverse Lunges",
  "Hollow Body Hold",
  "Bodyweight Squats",
  "Dumbbell Lunges",
  "Chest Flyes",
  "Chest Press",
  "Dumbbell Kickbacks",
  "Kettlebell Goblet Squat",
  "Jump Rope",
  "Cable Rows",
  "Pec Deck Machine",
  "Machine Shoulder Press",
  "Cable Crossover",
  "Stiff-Legged Deadlift",
  "Leg Raise",
  "Tricep Kickbacks",
  "Decline Bench Press",
  "Decline Dumbell Press",
  "Pull-up Bar Hang",
  "Seated Leg Press",
  "Hack Squat",
  "Single-Leg Romanian Deadlift",
  "Bear Crawl",
  "Plank with Shoulder Taps",
  "Sprint Intervals",
  "Jumping Lunges",
  "Spiderman Push-up",
  "High Knees",
  "Reverse Grip Bent Over Rows",
  "Renegade Rows",
  "Single-Leg Calf Raises",
  "Side Lunges",
  "Tire Flips",
  "Dumbbell Squat Thrusters",
  "Lateral Box Jumps",
  "Turkish Get-up",
  "Trap Bar Deadlift",
  "Dumbbell Front Raise",
  "Seated Leg Curl",
  "Bodyweight Hip Thrusts",
  "Chin-ups",
  "Wall Sit",
  "Seated Overhead Press",
  "Lateral Band Walks",
  "Landmine Press",
  "Pallof Press",
  "Zercher Squats",
  "Bent Over Reverse Flyes",
  "Standing Calf Raises",
  "Leg Press Machine",
  "Hamstring Curl Machine",
  "Dumbbell Step-ups",
];

export default exerciseNames;
