function RandomNiceMessage() {
  const niceMessages = [
    "You are so much more than a number on a scale.",
    "Your worth isn't determined by your weight.",
    "You're beautiful just the way you are.",
    "Your kindness shines brighter than any number.",
    "You're amazing inside and out.",
    "You're unique and that's your superpower.",
    "Confidence looks great on you.",
    "You have a heart of gold.",
    "You're loved for who you are.",
    "You're worthy of happiness.",
    "Your presence lights up the room.",
    "You inspire others with your strength.",
    "You're not defined by society's standards.",
    "Your personality is magnetic.",
    "You're deserving of self-love.",
    "You're so much stronger than you realize.",
    "You're more than enough.",
    "Your value goes beyond appearance.",
    "You're a beacon of positivity.",
    "You're capable of achieving anything.",
    "You radiate beauty from the inside out.",
    "You're a masterpiece in progress.",
    "Your self-worth is undeniable.",
    "You have the power to overcome challenges.",
    "You bring joy to those around you.",
    "Your spirit is unbreakable.",
    "You're important and irreplaceable.",
    "You're a symbol of resilience.",
    "You're a constant source of inspiration.",
    "Your journey is uniquely yours.",
    "You're not alone in your insecurities.",
    "You're cherished just as you are.",
    "You have so much to offer the world.",
    "You're defined by your character, not your weight.",
    "Your impact goes far beyond appearances.",
    "You're a true work of art.",
    "You possess incredible inner strength.",
    "You're valued for your heart and soul.",
    "You're braver than you believe.",
    "You're writing your own beautiful story.",
    "You deserve kindness and respect.",
    "You're loved exactly as you are.",
    "You're changing the world by being you.",
    "You have a unique and important purpose.",
    "You're worthy of all good things.",
    "You shine with authenticity.",
    "You're more than capable.",
    "You're not defined by any one thing.",
    "You're a constant source of hope.",
    "You're beautiful both inside and out.",
    "You're part of something bigger.",
    "You're loved beyond measure.",
    "You're accepted and cherished.",
    "You're worth every bit of love.",
    "You're allowed to embrace yourself.",
    "You're remarkable in every way.",
    "You have a heart full of compassion.",
    "You're changing lives just by being you.",
    "You're a true gift to this world.",
    "You're strong, resilient, and brave.",
    "You're defined by your actions and kindness.",
    "You're a beacon of light for others.",
    "You're loved for your essence.",
    "You have the power to rise above.",
    "You're a warrior on a unique journey.",
    "You're an extraordinary and genuine soul.",
    "You're worthy of all the good things life offers.",
    "You're perfect just as you are.",
    "You're loved for being authentically you.",
    "You're an inspiration to many.",
    "You're worth more than you know.",
    "You're a force of positivity.",
    "You're not alone on this path.",
    "You're beautiful inside and out.",
    "You're a source of joy for others.",
    "You're loved beyond your appearance.",
    "You're courageous and resilient.",
    "You have a heart that's made of gold.",
    "You're a masterpiece of strength.",
    "You're valued for your character.",
    "You're capable of amazing things.",
    "You're worth all the love and kindness.",
    "You're stronger than any doubts.",
    "You're cherished just as you are.",
    "You're making a positive impact.",
    "You're beautiful in your uniqueness.",
    "You're enough, exactly as you are.",
    "You're part of a community that cares.",
    "You're changing lives with your presence.",
    "You're loved for your heart and soul.",
    "You're capable of facing anything.",
    "You're a ray of sunshine to others.",
    "You're embraced for being you.",
  ];

  return niceMessages[Math.floor(Math.random() * niceMessages.length)];
}

export default RandomNiceMessage;
